### ISSUE TITLE
Create a relationship between user and branch

### ISSUE THREAD

**Issue by ivorobioff** [ivorobioff/veronica.tutorial#3]
You need to create an array of branches. The array of branches is similar to the array of users. 

```php
return [
    [
        'id' => 1,
        'location' => [
            'address' => '123 Market St',
            'state' => 'CA',
            'city' => 'San Francisco',
           'zip' => 94132 
        ]
    ],
    ...
],
```
Next, you  need to assign branches to users by adding the following to entries in the users array:

```php
return [
     [
          ...
          'branchId' => {branchId},
          ...
     ]
]
```

where `{branchId}` is id of a specific branch.

Finally, on the `home.php` page you should print the message:

Location:
123 Market St.
San Francisco,
CA 94132

**Comment by iuniavs** [comment]
Done

**Comment by ivorobioff** [comment]
Excellent work!

A small note though, please use single quotes `'` instead of double quotes `"` when dealing with strings in PHP. Double quotes are okay for HTML.
