### ISSUE TITLE
Need to show cars per branch

### ISSUE THREAD

**Issue by ivorobioff** [ivorobioff/veronica.tutorial#4]
Again, as you did with users, you should create an array of cars as in the example:

```php
return [
    [
        'id' => 1,
        'name' => 'Citroen C4',
        'image' => 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Citro%C3%ABn_C4_Exclusive_%28II%29_%E2%80%93_Frontansicht%2C_20._Juni_2012%2C_Wuppertal.jpg'
        'cost' => 52.99,
        'isAvailable' => true,
        'class' => 'Luxury'
        'branchId' => 2
    ],
    ...
];
```
 _(Please create at least 10 cars)_

Next, you need to show on the `home.php` page cars that belongs to the branch to which the logged-in user is assigned.

Moreover, you should group the output by class to which cars belong. For example:

##### Economy

[Lada 2107 (not available)](car.php)
[Chevrolet XL891 (available)](car.php)

##### Standard

_No cars_

##### Luxury

[Citroen C4](car.php (available))

and so on...

The link should lead to the `car.php` page where should output a complete information about the car and price.

**Comment by iuniavs** [comment]
Done
